name: generador_qr_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  share_plus: ^7.2.2
  webview_flutter: ^4.2.2
  url_launcher: ^6.2.5

  # âœ… Bluetooth: usar BLE (compatible con iOS y Android)
  flutter_blue_plus: ^1.35.1

  permission_handler: ^11.0.1

  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10

  qr_flutter: ^4.1.0
  socket_io_client: ^2.0.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_icon.jpeg
    - assets/logo.gif

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon.jpeg"
  remove_alpha_ios: true
